#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternFollowProgramming
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="INTERN")]
	public partial class internclassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIntershipInformation(IntershipInformation instance);
    partial void UpdateIntershipInformation(IntershipInformation instance);
    partial void DeleteIntershipInformation(IntershipInformation instance);
    partial void Insertintern(intern instance);
    partial void Updateintern(intern instance);
    partial void Deleteintern(intern instance);
    #endregion
		
		public internclassesDataContext() : 
				base(global::InternFollowProgramming.Properties.Settings.Default.INTERNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public internclassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public internclassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public internclassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public internclassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IntershipInformation> IntershipInformation
		{
			get
			{
				return this.GetTable<IntershipInformation>();
			}
		}
		
		public System.Data.Linq.Table<intern> intern
		{
			get
			{
				return this.GetTable<intern>();
			}
		}
		
		public System.Data.Linq.Table<kullanıcı> kullanıcı
		{
			get
			{
				return this.GetTable<kullanıcı>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IntershipInformation")]
	public partial class IntershipInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _stajyer_id;
		
		private string _staj_kabul_durumu;
		
		private string _staj_basvuru_turu;
		
		private string _staj_yılı;
		
		private string _staj_donem;
		
		private string _staj_konusu;
		
		private string _staj_baslangıc_tarihi;
		
		private string _staj_bitis_tarihi;
		
		private string _staj_süresi;
		
		private string _staj_bas_kalan_sure;
		
		private string _staj_konuları;
		
		private string _staj_servis;
		
		private string _staj_plaka;
		
		private string _staj_durumu;
		
		private string _mentor;
		
		private string _acıklama;
		
		private string _sigorta_evrak_durumu;
		
		private string _referans_adı;
		
		private string _referans_telefon;
		
		private string _referans_adres;
		
		private string _referans_e_posta;
		
		private string _okul_turu;
		
		private string _okul_adı;
		
		private string _okul_sehir;
		
		private string _bolum_adı;
		
		private string _sınıf;
		
		private string _okul_no;
		
		private string _okul_puan;
		
		private System.Nullable<long> _tc_kimlikno;
		
		private EntityRef<intern> _intern;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstajyer_idChanging(long value);
    partial void Onstajyer_idChanged();
    partial void Onstaj_kabul_durumuChanging(string value);
    partial void Onstaj_kabul_durumuChanged();
    partial void Onstaj_basvuru_turuChanging(string value);
    partial void Onstaj_basvuru_turuChanged();
    partial void Onstaj_yılıChanging(string value);
    partial void Onstaj_yılıChanged();
    partial void Onstaj_donemChanging(string value);
    partial void Onstaj_donemChanged();
    partial void Onstaj_konusuChanging(string value);
    partial void Onstaj_konusuChanged();
    partial void Onstaj_baslangıc_tarihiChanging(string value);
    partial void Onstaj_baslangıc_tarihiChanged();
    partial void Onstaj_bitis_tarihiChanging(string value);
    partial void Onstaj_bitis_tarihiChanged();
    partial void Onstaj_süresiChanging(string value);
    partial void Onstaj_süresiChanged();
    partial void Onstaj_bas_kalan_sureChanging(string value);
    partial void Onstaj_bas_kalan_sureChanged();
    partial void Onstaj_konularıChanging(string value);
    partial void Onstaj_konularıChanged();
    partial void Onstaj_servisChanging(string value);
    partial void Onstaj_servisChanged();
    partial void Onstaj_plakaChanging(string value);
    partial void Onstaj_plakaChanged();
    partial void Onstaj_durumuChanging(string value);
    partial void Onstaj_durumuChanged();
    partial void OnmentorChanging(string value);
    partial void OnmentorChanged();
    partial void OnacıklamaChanging(string value);
    partial void OnacıklamaChanged();
    partial void Onsigorta_evrak_durumuChanging(string value);
    partial void Onsigorta_evrak_durumuChanged();
    partial void Onreferans_adıChanging(string value);
    partial void Onreferans_adıChanged();
    partial void Onreferans_telefonChanging(string value);
    partial void Onreferans_telefonChanged();
    partial void Onreferans_adresChanging(string value);
    partial void Onreferans_adresChanged();
    partial void Onreferans_e_postaChanging(string value);
    partial void Onreferans_e_postaChanged();
    partial void Onokul_turuChanging(string value);
    partial void Onokul_turuChanged();
    partial void Onokul_adıChanging(string value);
    partial void Onokul_adıChanged();
    partial void Onokul_sehirChanging(string value);
    partial void Onokul_sehirChanged();
    partial void Onbolum_adıChanging(string value);
    partial void Onbolum_adıChanged();
    partial void OnsınıfChanging(string value);
    partial void OnsınıfChanged();
    partial void Onokul_noChanging(string value);
    partial void Onokul_noChanged();
    partial void Onokul_puanChanging(string value);
    partial void Onokul_puanChanged();
    partial void Ontc_kimliknoChanging(System.Nullable<long> value);
    partial void Ontc_kimliknoChanged();
    #endregion
		
		public IntershipInformation()
		{
			this._intern = default(EntityRef<intern>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stajyer_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long stajyer_id
		{
			get
			{
				return this._stajyer_id;
			}
			set
			{
				if ((this._stajyer_id != value))
				{
					this.Onstajyer_idChanging(value);
					this.SendPropertyChanging();
					this._stajyer_id = value;
					this.SendPropertyChanged("stajyer_id");
					this.Onstajyer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_kabul_durumu", DbType="NVarChar(MAX)")]
		public string staj_kabul_durumu
		{
			get
			{
				return this._staj_kabul_durumu;
			}
			set
			{
				if ((this._staj_kabul_durumu != value))
				{
					this.Onstaj_kabul_durumuChanging(value);
					this.SendPropertyChanging();
					this._staj_kabul_durumu = value;
					this.SendPropertyChanged("staj_kabul_durumu");
					this.Onstaj_kabul_durumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_basvuru_turu", DbType="NVarChar(MAX)")]
		public string staj_basvuru_turu
		{
			get
			{
				return this._staj_basvuru_turu;
			}
			set
			{
				if ((this._staj_basvuru_turu != value))
				{
					this.Onstaj_basvuru_turuChanging(value);
					this.SendPropertyChanging();
					this._staj_basvuru_turu = value;
					this.SendPropertyChanged("staj_basvuru_turu");
					this.Onstaj_basvuru_turuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_yılı", DbType="NVarChar(MAX)")]
		public string staj_yılı
		{
			get
			{
				return this._staj_yılı;
			}
			set
			{
				if ((this._staj_yılı != value))
				{
					this.Onstaj_yılıChanging(value);
					this.SendPropertyChanging();
					this._staj_yılı = value;
					this.SendPropertyChanged("staj_yılı");
					this.Onstaj_yılıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_donem", DbType="NVarChar(MAX)")]
		public string staj_donem
		{
			get
			{
				return this._staj_donem;
			}
			set
			{
				if ((this._staj_donem != value))
				{
					this.Onstaj_donemChanging(value);
					this.SendPropertyChanging();
					this._staj_donem = value;
					this.SendPropertyChanged("staj_donem");
					this.Onstaj_donemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_konusu", DbType="NVarChar(MAX)")]
		public string staj_konusu
		{
			get
			{
				return this._staj_konusu;
			}
			set
			{
				if ((this._staj_konusu != value))
				{
					this.Onstaj_konusuChanging(value);
					this.SendPropertyChanging();
					this._staj_konusu = value;
					this.SendPropertyChanged("staj_konusu");
					this.Onstaj_konusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_baslangıc_tarihi", DbType="NVarChar(MAX)")]
		public string staj_baslangıc_tarihi
		{
			get
			{
				return this._staj_baslangıc_tarihi;
			}
			set
			{
				if ((this._staj_baslangıc_tarihi != value))
				{
					this.Onstaj_baslangıc_tarihiChanging(value);
					this.SendPropertyChanging();
					this._staj_baslangıc_tarihi = value;
					this.SendPropertyChanged("staj_baslangıc_tarihi");
					this.Onstaj_baslangıc_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_bitis_tarihi", DbType="NVarChar(MAX)")]
		public string staj_bitis_tarihi
		{
			get
			{
				return this._staj_bitis_tarihi;
			}
			set
			{
				if ((this._staj_bitis_tarihi != value))
				{
					this.Onstaj_bitis_tarihiChanging(value);
					this.SendPropertyChanging();
					this._staj_bitis_tarihi = value;
					this.SendPropertyChanged("staj_bitis_tarihi");
					this.Onstaj_bitis_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_süresi", DbType="NVarChar(MAX)")]
		public string staj_süresi
		{
			get
			{
				return this._staj_süresi;
			}
			set
			{
				if ((this._staj_süresi != value))
				{
					this.Onstaj_süresiChanging(value);
					this.SendPropertyChanging();
					this._staj_süresi = value;
					this.SendPropertyChanged("staj_süresi");
					this.Onstaj_süresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_bas_kalan_sure", DbType="NVarChar(MAX)")]
		public string staj_bas_kalan_sure
		{
			get
			{
				return this._staj_bas_kalan_sure;
			}
			set
			{
				if ((this._staj_bas_kalan_sure != value))
				{
					this.Onstaj_bas_kalan_sureChanging(value);
					this.SendPropertyChanging();
					this._staj_bas_kalan_sure = value;
					this.SendPropertyChanged("staj_bas_kalan_sure");
					this.Onstaj_bas_kalan_sureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_konuları", DbType="NVarChar(MAX)")]
		public string staj_konuları
		{
			get
			{
				return this._staj_konuları;
			}
			set
			{
				if ((this._staj_konuları != value))
				{
					this.Onstaj_konularıChanging(value);
					this.SendPropertyChanging();
					this._staj_konuları = value;
					this.SendPropertyChanged("staj_konuları");
					this.Onstaj_konularıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_servis", DbType="NVarChar(MAX)")]
		public string staj_servis
		{
			get
			{
				return this._staj_servis;
			}
			set
			{
				if ((this._staj_servis != value))
				{
					this.Onstaj_servisChanging(value);
					this.SendPropertyChanging();
					this._staj_servis = value;
					this.SendPropertyChanged("staj_servis");
					this.Onstaj_servisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_plaka", DbType="NVarChar(MAX)")]
		public string staj_plaka
		{
			get
			{
				return this._staj_plaka;
			}
			set
			{
				if ((this._staj_plaka != value))
				{
					this.Onstaj_plakaChanging(value);
					this.SendPropertyChanging();
					this._staj_plaka = value;
					this.SendPropertyChanged("staj_plaka");
					this.Onstaj_plakaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_durumu", DbType="NVarChar(MAX)")]
		public string staj_durumu
		{
			get
			{
				return this._staj_durumu;
			}
			set
			{
				if ((this._staj_durumu != value))
				{
					this.Onstaj_durumuChanging(value);
					this.SendPropertyChanging();
					this._staj_durumu = value;
					this.SendPropertyChanged("staj_durumu");
					this.Onstaj_durumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mentor", DbType="NVarChar(MAX)")]
		public string mentor
		{
			get
			{
				return this._mentor;
			}
			set
			{
				if ((this._mentor != value))
				{
					this.OnmentorChanging(value);
					this.SendPropertyChanging();
					this._mentor = value;
					this.SendPropertyChanged("mentor");
					this.OnmentorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acıklama", DbType="NVarChar(MAX)")]
		public string acıklama
		{
			get
			{
				return this._acıklama;
			}
			set
			{
				if ((this._acıklama != value))
				{
					this.OnacıklamaChanging(value);
					this.SendPropertyChanging();
					this._acıklama = value;
					this.SendPropertyChanged("acıklama");
					this.OnacıklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigorta_evrak_durumu", DbType="NVarChar(MAX)")]
		public string sigorta_evrak_durumu
		{
			get
			{
				return this._sigorta_evrak_durumu;
			}
			set
			{
				if ((this._sigorta_evrak_durumu != value))
				{
					this.Onsigorta_evrak_durumuChanging(value);
					this.SendPropertyChanging();
					this._sigorta_evrak_durumu = value;
					this.SendPropertyChanged("sigorta_evrak_durumu");
					this.Onsigorta_evrak_durumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referans_adı", DbType="NVarChar(MAX)")]
		public string referans_adı
		{
			get
			{
				return this._referans_adı;
			}
			set
			{
				if ((this._referans_adı != value))
				{
					this.Onreferans_adıChanging(value);
					this.SendPropertyChanging();
					this._referans_adı = value;
					this.SendPropertyChanged("referans_adı");
					this.Onreferans_adıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referans_telefon", DbType="NVarChar(MAX)")]
		public string referans_telefon
		{
			get
			{
				return this._referans_telefon;
			}
			set
			{
				if ((this._referans_telefon != value))
				{
					this.Onreferans_telefonChanging(value);
					this.SendPropertyChanging();
					this._referans_telefon = value;
					this.SendPropertyChanged("referans_telefon");
					this.Onreferans_telefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referans_adres", DbType="NVarChar(MAX)")]
		public string referans_adres
		{
			get
			{
				return this._referans_adres;
			}
			set
			{
				if ((this._referans_adres != value))
				{
					this.Onreferans_adresChanging(value);
					this.SendPropertyChanging();
					this._referans_adres = value;
					this.SendPropertyChanged("referans_adres");
					this.Onreferans_adresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referans_e_posta", DbType="NVarChar(MAX)")]
		public string referans_e_posta
		{
			get
			{
				return this._referans_e_posta;
			}
			set
			{
				if ((this._referans_e_posta != value))
				{
					this.Onreferans_e_postaChanging(value);
					this.SendPropertyChanging();
					this._referans_e_posta = value;
					this.SendPropertyChanged("referans_e_posta");
					this.Onreferans_e_postaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_turu", DbType="NVarChar(MAX)")]
		public string okul_turu
		{
			get
			{
				return this._okul_turu;
			}
			set
			{
				if ((this._okul_turu != value))
				{
					this.Onokul_turuChanging(value);
					this.SendPropertyChanging();
					this._okul_turu = value;
					this.SendPropertyChanged("okul_turu");
					this.Onokul_turuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_adı", DbType="NVarChar(MAX)")]
		public string okul_adı
		{
			get
			{
				return this._okul_adı;
			}
			set
			{
				if ((this._okul_adı != value))
				{
					this.Onokul_adıChanging(value);
					this.SendPropertyChanging();
					this._okul_adı = value;
					this.SendPropertyChanged("okul_adı");
					this.Onokul_adıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_sehir", DbType="NVarChar(MAX)")]
		public string okul_sehir
		{
			get
			{
				return this._okul_sehir;
			}
			set
			{
				if ((this._okul_sehir != value))
				{
					this.Onokul_sehirChanging(value);
					this.SendPropertyChanging();
					this._okul_sehir = value;
					this.SendPropertyChanged("okul_sehir");
					this.Onokul_sehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_adı", DbType="NVarChar(MAX)")]
		public string bolum_adı
		{
			get
			{
				return this._bolum_adı;
			}
			set
			{
				if ((this._bolum_adı != value))
				{
					this.Onbolum_adıChanging(value);
					this.SendPropertyChanging();
					this._bolum_adı = value;
					this.SendPropertyChanged("bolum_adı");
					this.Onbolum_adıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sınıf", DbType="NVarChar(MAX)")]
		public string sınıf
		{
			get
			{
				return this._sınıf;
			}
			set
			{
				if ((this._sınıf != value))
				{
					this.OnsınıfChanging(value);
					this.SendPropertyChanging();
					this._sınıf = value;
					this.SendPropertyChanged("sınıf");
					this.OnsınıfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_no", DbType="NVarChar(MAX)")]
		public string okul_no
		{
			get
			{
				return this._okul_no;
			}
			set
			{
				if ((this._okul_no != value))
				{
					this.Onokul_noChanging(value);
					this.SendPropertyChanging();
					this._okul_no = value;
					this.SendPropertyChanged("okul_no");
					this.Onokul_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okul_puan", DbType="NVarChar(MAX)")]
		public string okul_puan
		{
			get
			{
				return this._okul_puan;
			}
			set
			{
				if ((this._okul_puan != value))
				{
					this.Onokul_puanChanging(value);
					this.SendPropertyChanging();
					this._okul_puan = value;
					this.SendPropertyChanged("okul_puan");
					this.Onokul_puanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_kimlikno", DbType="BigInt")]
		public System.Nullable<long> tc_kimlikno
		{
			get
			{
				return this._tc_kimlikno;
			}
			set
			{
				if ((this._tc_kimlikno != value))
				{
					if (this._intern.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontc_kimliknoChanging(value);
					this.SendPropertyChanging();
					this._tc_kimlikno = value;
					this.SendPropertyChanged("tc_kimlikno");
					this.Ontc_kimliknoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="intern_IntershipInformation", Storage="_intern", ThisKey="tc_kimlikno", OtherKey="tc_kimlikno", IsForeignKey=true)]
		public intern intern
		{
			get
			{
				return this._intern.Entity;
			}
			set
			{
				intern previousValue = this._intern.Entity;
				if (((previousValue != value) 
							|| (this._intern.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._intern.Entity = null;
						previousValue.IntershipInformation.Remove(this);
					}
					this._intern.Entity = value;
					if ((value != null))
					{
						value.IntershipInformation.Add(this);
						this._tc_kimlikno = value.tc_kimlikno;
					}
					else
					{
						this._tc_kimlikno = default(Nullable<long>);
					}
					this.SendPropertyChanged("intern");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.intern")]
	public partial class intern : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _tc_kimlikno;
		
		private string _ad_soyad;
		
		private string _baba_adı;
		
		private string _anne_adı;
		
		private string _d_yeri;
		
		private string _d_tarih;
		
		private string _uyrugu;
		
		private string _cinsiyet;
		
		private string _ev_tel;
		
		private string _cep_tel;
		
		private string _adres;
		
		private string _e_posta;
		
		private string _web_adres;
		
		private string _boy;
		
		private string _agırlık;
		
		private string _kan_grubu;
		
		private string _iban;
		
		private string _acil_adsoyad;
		
		private string _acil_adres;
		
		private string _acil_akrabalık_derecesi;
		
		private string _acil_telefon_no;
		
		private string _acil_e_posta;
		
		private EntitySet<IntershipInformation> _IntershipInformation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontc_kimliknoChanging(long value);
    partial void Ontc_kimliknoChanged();
    partial void Onad_soyadChanging(string value);
    partial void Onad_soyadChanged();
    partial void Onbaba_adıChanging(string value);
    partial void Onbaba_adıChanged();
    partial void Onanne_adıChanging(string value);
    partial void Onanne_adıChanged();
    partial void Ond_yeriChanging(string value);
    partial void Ond_yeriChanged();
    partial void Ond_tarihChanging(string value);
    partial void Ond_tarihChanged();
    partial void OnuyruguChanging(string value);
    partial void OnuyruguChanged();
    partial void OncinsiyetChanging(string value);
    partial void OncinsiyetChanged();
    partial void Onev_telChanging(string value);
    partial void Onev_telChanged();
    partial void Oncep_telChanging(string value);
    partial void Oncep_telChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void One_postaChanging(string value);
    partial void One_postaChanged();
    partial void Onweb_adresChanging(string value);
    partial void Onweb_adresChanged();
    partial void OnboyChanging(string value);
    partial void OnboyChanged();
    partial void OnagırlıkChanging(string value);
    partial void OnagırlıkChanged();
    partial void Onkan_grubuChanging(string value);
    partial void Onkan_grubuChanged();
    partial void OnibanChanging(string value);
    partial void OnibanChanged();
    partial void Onacil_adsoyadChanging(string value);
    partial void Onacil_adsoyadChanged();
    partial void Onacil_adresChanging(string value);
    partial void Onacil_adresChanged();
    partial void Onacil_akrabalık_derecesiChanging(string value);
    partial void Onacil_akrabalık_derecesiChanged();
    partial void Onacil_telefon_noChanging(string value);
    partial void Onacil_telefon_noChanged();
    partial void Onacil_e_postaChanging(string value);
    partial void Onacil_e_postaChanged();
    #endregion
		
		public intern()
		{
			this._IntershipInformation = new EntitySet<IntershipInformation>(new Action<IntershipInformation>(this.attach_IntershipInformation), new Action<IntershipInformation>(this.detach_IntershipInformation));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_kimlikno", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long tc_kimlikno
		{
			get
			{
				return this._tc_kimlikno;
			}
			set
			{
				if ((this._tc_kimlikno != value))
				{
					this.Ontc_kimliknoChanging(value);
					this.SendPropertyChanging();
					this._tc_kimlikno = value;
					this.SendPropertyChanged("tc_kimlikno");
					this.Ontc_kimliknoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_soyad", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ad_soyad
		{
			get
			{
				return this._ad_soyad;
			}
			set
			{
				if ((this._ad_soyad != value))
				{
					this.Onad_soyadChanging(value);
					this.SendPropertyChanging();
					this._ad_soyad = value;
					this.SendPropertyChanged("ad_soyad");
					this.Onad_soyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baba_adı", DbType="NVarChar(MAX)")]
		public string baba_adı
		{
			get
			{
				return this._baba_adı;
			}
			set
			{
				if ((this._baba_adı != value))
				{
					this.Onbaba_adıChanging(value);
					this.SendPropertyChanging();
					this._baba_adı = value;
					this.SendPropertyChanged("baba_adı");
					this.Onbaba_adıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anne_adı", DbType="NVarChar(MAX)")]
		public string anne_adı
		{
			get
			{
				return this._anne_adı;
			}
			set
			{
				if ((this._anne_adı != value))
				{
					this.Onanne_adıChanging(value);
					this.SendPropertyChanging();
					this._anne_adı = value;
					this.SendPropertyChanged("anne_adı");
					this.Onanne_adıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_yeri", DbType="NVarChar(MAX)")]
		public string d_yeri
		{
			get
			{
				return this._d_yeri;
			}
			set
			{
				if ((this._d_yeri != value))
				{
					this.Ond_yeriChanging(value);
					this.SendPropertyChanging();
					this._d_yeri = value;
					this.SendPropertyChanged("d_yeri");
					this.Ond_yeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_tarih", DbType="NVarChar(MAX)")]
		public string d_tarih
		{
			get
			{
				return this._d_tarih;
			}
			set
			{
				if ((this._d_tarih != value))
				{
					this.Ond_tarihChanging(value);
					this.SendPropertyChanging();
					this._d_tarih = value;
					this.SendPropertyChanged("d_tarih");
					this.Ond_tarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyrugu", DbType="NVarChar(MAX)")]
		public string uyrugu
		{
			get
			{
				return this._uyrugu;
			}
			set
			{
				if ((this._uyrugu != value))
				{
					this.OnuyruguChanging(value);
					this.SendPropertyChanging();
					this._uyrugu = value;
					this.SendPropertyChanged("uyrugu");
					this.OnuyruguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="NVarChar(MAX)")]
		public string cinsiyet
		{
			get
			{
				return this._cinsiyet;
			}
			set
			{
				if ((this._cinsiyet != value))
				{
					this.OncinsiyetChanging(value);
					this.SendPropertyChanging();
					this._cinsiyet = value;
					this.SendPropertyChanged("cinsiyet");
					this.OncinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ev_tel", DbType="NVarChar(MAX)")]
		public string ev_tel
		{
			get
			{
				return this._ev_tel;
			}
			set
			{
				if ((this._ev_tel != value))
				{
					this.Onev_telChanging(value);
					this.SendPropertyChanging();
					this._ev_tel = value;
					this.SendPropertyChanged("ev_tel");
					this.Onev_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep_tel", DbType="NVarChar(MAX)")]
		public string cep_tel
		{
			get
			{
				return this._cep_tel;
			}
			set
			{
				if ((this._cep_tel != value))
				{
					this.Oncep_telChanging(value);
					this.SendPropertyChanging();
					this._cep_tel = value;
					this.SendPropertyChanged("cep_tel");
					this.Oncep_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NVarChar(MAX)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_posta", DbType="NVarChar(MAX)")]
		public string e_posta
		{
			get
			{
				return this._e_posta;
			}
			set
			{
				if ((this._e_posta != value))
				{
					this.One_postaChanging(value);
					this.SendPropertyChanging();
					this._e_posta = value;
					this.SendPropertyChanged("e_posta");
					this.One_postaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_adres", DbType="NVarChar(MAX)")]
		public string web_adres
		{
			get
			{
				return this._web_adres;
			}
			set
			{
				if ((this._web_adres != value))
				{
					this.Onweb_adresChanging(value);
					this.SendPropertyChanging();
					this._web_adres = value;
					this.SendPropertyChanged("web_adres");
					this.Onweb_adresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boy", DbType="NVarChar(MAX)")]
		public string boy
		{
			get
			{
				return this._boy;
			}
			set
			{
				if ((this._boy != value))
				{
					this.OnboyChanging(value);
					this.SendPropertyChanging();
					this._boy = value;
					this.SendPropertyChanged("boy");
					this.OnboyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agırlık", DbType="NVarChar(MAX)")]
		public string agırlık
		{
			get
			{
				return this._agırlık;
			}
			set
			{
				if ((this._agırlık != value))
				{
					this.OnagırlıkChanging(value);
					this.SendPropertyChanging();
					this._agırlık = value;
					this.SendPropertyChanged("agırlık");
					this.OnagırlıkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kan_grubu", DbType="NVarChar(MAX)")]
		public string kan_grubu
		{
			get
			{
				return this._kan_grubu;
			}
			set
			{
				if ((this._kan_grubu != value))
				{
					this.Onkan_grubuChanging(value);
					this.SendPropertyChanging();
					this._kan_grubu = value;
					this.SendPropertyChanged("kan_grubu");
					this.Onkan_grubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iban", DbType="NVarChar(MAX)")]
		public string iban
		{
			get
			{
				return this._iban;
			}
			set
			{
				if ((this._iban != value))
				{
					this.OnibanChanging(value);
					this.SendPropertyChanging();
					this._iban = value;
					this.SendPropertyChanged("iban");
					this.OnibanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acil_adsoyad", DbType="NVarChar(MAX)")]
		public string acil_adsoyad
		{
			get
			{
				return this._acil_adsoyad;
			}
			set
			{
				if ((this._acil_adsoyad != value))
				{
					this.Onacil_adsoyadChanging(value);
					this.SendPropertyChanging();
					this._acil_adsoyad = value;
					this.SendPropertyChanged("acil_adsoyad");
					this.Onacil_adsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acil_adres", DbType="NVarChar(MAX)")]
		public string acil_adres
		{
			get
			{
				return this._acil_adres;
			}
			set
			{
				if ((this._acil_adres != value))
				{
					this.Onacil_adresChanging(value);
					this.SendPropertyChanging();
					this._acil_adres = value;
					this.SendPropertyChanged("acil_adres");
					this.Onacil_adresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acil_akrabalık_derecesi", DbType="NVarChar(MAX)")]
		public string acil_akrabalık_derecesi
		{
			get
			{
				return this._acil_akrabalık_derecesi;
			}
			set
			{
				if ((this._acil_akrabalık_derecesi != value))
				{
					this.Onacil_akrabalık_derecesiChanging(value);
					this.SendPropertyChanging();
					this._acil_akrabalık_derecesi = value;
					this.SendPropertyChanged("acil_akrabalık_derecesi");
					this.Onacil_akrabalık_derecesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acil_telefon_no", DbType="NVarChar(MAX)")]
		public string acil_telefon_no
		{
			get
			{
				return this._acil_telefon_no;
			}
			set
			{
				if ((this._acil_telefon_no != value))
				{
					this.Onacil_telefon_noChanging(value);
					this.SendPropertyChanging();
					this._acil_telefon_no = value;
					this.SendPropertyChanged("acil_telefon_no");
					this.Onacil_telefon_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acil_e_posta", DbType="NVarChar(MAX)")]
		public string acil_e_posta
		{
			get
			{
				return this._acil_e_posta;
			}
			set
			{
				if ((this._acil_e_posta != value))
				{
					this.Onacil_e_postaChanging(value);
					this.SendPropertyChanging();
					this._acil_e_posta = value;
					this.SendPropertyChanged("acil_e_posta");
					this.Onacil_e_postaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="intern_IntershipInformation", Storage="_IntershipInformation", ThisKey="tc_kimlikno", OtherKey="tc_kimlikno")]
		public EntitySet<IntershipInformation> IntershipInformation
		{
			get
			{
				return this._IntershipInformation;
			}
			set
			{
				this._IntershipInformation.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IntershipInformation(IntershipInformation entity)
		{
			this.SendPropertyChanging();
			entity.intern = this;
		}
		
		private void detach_IntershipInformation(IntershipInformation entity)
		{
			this.SendPropertyChanging();
			entity.intern = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kullanıcı")]
	public partial class kullanıcı
	{
		
		private string _kullanıcı_adı;
		
		private string _sifre;
		
		public kullanıcı()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanıcı_adı", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string kullanıcı_adı
		{
			get
			{
				return this._kullanıcı_adı;
			}
			set
			{
				if ((this._kullanıcı_adı != value))
				{
					this._kullanıcı_adı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this._sifre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
